site_name: The Game
site_url: https://DeckofAdventures.github.io/TheGame
site_description: Deck of Adventures Documents
site_author: CBroz1

repo_url: https://github.com/DeckofAdventures/TheGame
docs_dir: ./src/
edit_uri: blob/main/docs/src/

theme:
    name: material
    custom_dir: overrides
    logo: stylesheets/Logo_Transparent.png
    favicon: stylesheets/spades.svg
    features:
      - toc.integrate
      - navigation.sections
      - navigation.expand
      - navigation.top
    palette:
      - media: "(prefers-color-scheme: light)"
        scheme: my-default
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
    disable_nav_previous_next: true
    disable_nav_search: false
    navigation_depth: 2
    locale: en
    shortcuts:
        help:      72 # h # doesn't seem to be working
        next:      78 # n
        previous:  80 # p
        search:    83 # s
    features:
      - navigation.instant   # saves loading time - 1 browser page
      - navigation.tracking  # even with above, changes URL by section
      - navigation.top
      # - navigation.tabs      # moves top level heading to tabs
      # - toc.integrate        # move TOC to left
      - search.suggest
      - search.share

nav:
  - Home:                   index.md
  - Mechanics:
    - Quickstart Guide:     1_Mechanics/01_PlayerGuide_Brief.md
    - Full Guide:           1_Mechanics/01_PlayerGuide_Full.md
    - GM Guide:             1_Mechanics/02_GMGuide.md
    - Character Creation:   1_Mechanics/03_CharacterCreation.md
    - Powers:               1_Mechanics/04_Powers.md
    - Vulnerabilities:      1_Mechanics/05_Vulnerabilities.md
    - Bestiary:             1_Mechanics/06_Bestiary.md
    - Items:                1_Mechanics/07_Items.md
    - Glossary:             1_Mechanics/99_Glossary.md
    - Tools:                1_Mechanics/Visual_Tools/README.md
    - Premades:             1_Mechanics/PremadeCharacters/README.md
  - Development:
    - Community:            2_Development/01_Community.md
    - Design:               2_Development/02_Design_Document.md
    - Timeline:             2_Development/03_Development_Timeline.md
    - Change Log:           CHANGELOG.md
    - Contributions:        CONTRIBUTING.md
    - Code of Conduct:      CODE_OF_CONDUCT.md
    - License Info:         LICENSE.md
  - API: api/ # defer to gen-files + literate-nav

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - exclude:
      glob:
        - "temp*"
        - "0*yaml"
  - mike:
      canonical_version: latest
      css_dir: stylesheets
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            members_order: source      
            group_by_category: false
            line_length: 88
  - gen-files:
      scripts:
      - ./src/api/make_pages.py
  - literate-nav:
      nav_file: navigation.md'
  - exclude-search:
      exclude:
        - "*/navigation.md"
    # - include-markdown # https://github.com/mondeja/mkdocs-include-markdown-plugin
    # when use, add mkdocs-include-markdown-plugin to pip list

markdown_extensions:
  - attr_list
  - tables
  - toc:
      permalink: true

extra:
  generator: false # Disable watermark
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DeckofAdventures/TheGame
    - icon: fontawesome/brands/discord
      link: https://discord.gg/dk6RfWgPHF
  version:
    provider: mike
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by opening a
            <a href="https://github.com/DeckofAdventures/TheGame/issues/new?assignees=&labels=question&title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">GitHub issue</a>.
